//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR5_KozlovskiyDA_PR22101.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public long doc_id { get; set; }
        public long order_id { get; set; }
        public System.DateTime create_datetime { get; set; }
        public string doc_link { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
