//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR5_KozlovskiyDA_PR22101.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drinks
    {
        public Drinks()
        {
            this.DrinksAndOrders = new HashSet<DrinksAndOrders>();
            this.RawMaterialsAndDrinks = new HashSet<RawMaterialsAndDrinks>();
        }
    
        public long drink_id { get; set; }
        public string drink_name { get; set; }
        public string drink_description { get; set; }
        public string drink_compoud { get; set; }
    
        public virtual ICollection<DrinksAndOrders> DrinksAndOrders { get; set; }
        public virtual ICollection<RawMaterialsAndDrinks> RawMaterialsAndDrinks { get; set; }
    }
}
