//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR5_KozlovskiyDA_PR22101.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.Documents = new HashSet<Documents>();
            this.DrinksAndOrders = new HashSet<DrinksAndOrders>();
        }
    
        public long order_id { get; set; }
        public long user_id { get; set; }
        public long rmd_id { get; set; }
        public System.DateTime date_start_id { get; set; }
        public System.DateTime date_end_id { get; set; }
        public byte ready { get; set; }
        public decimal cost { get; set; }
        public long payment_id { get; set; }
    
        public virtual ICollection<Documents> Documents { get; set; }
        public virtual ICollection<DrinksAndOrders> DrinksAndOrders { get; set; }
        public virtual Payments Payments { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
