//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR5_KozlovskiyDA_PR22101.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterials
    {
        public RawMaterials()
        {
            this.RawMaterialsAndDrinks = new HashSet<RawMaterialsAndDrinks>();
        }
    
        public long rm_id { get; set; }
        public string rm_name { get; set; }
        public long rm_countKg { get; set; }
    
        public virtual ICollection<RawMaterialsAndDrinks> RawMaterialsAndDrinks { get; set; }
    }
}
