//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR5_KozlovskiyDA_PR22101.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialsAndDrinks
    {
        public long rmd_id { get; set; }
        public long rm_id { get; set; }
        public long drink_id { get; set; }
        public long rm_mass { get; set; }
    
        public virtual Drinks Drinks { get; set; }
        public virtual RawMaterials RawMaterials { get; set; }
    }
}
